### ISSUE TITLE
for what reason to use dry?

### ISSUE THREAD

**Issue by simonoff** [waiting-for-dev/warden-jwt_auth#14]
Hello, you have done a great job!
But I can't use your library because instead of have dependency only on warden it has much more, which is not comfortable for me. Is there is some possibilities to remove dry fully?

**Comment by waiting-for-dev** [comment]
Hi @simonoff ,

I relied on two dry organization gems in order not to reinvent the wheel here:

- dry-configuration is very useful in order that not every gem makes its own configuration system
- dry-auto_inject is very useful to decouple components. It makes testing easier and allows advanced custom usage of the gem in a very convenient way.

So I think that both dependencies bring added value to our gem, so I still think they are good choices. Also keep in mind that all gems in dry organization are very focused to address a single responsibility.
