### ISSUE TITLE
Feature Request: support of other algorithms for signing

### ISSUE THREAD

**Issue by tilo** [waiting-for-dev/warden-jwt_auth#17]
https://github.com/jwt/ruby-jwt  supports a lot of other algorithms, e.g. RS-*, ES-*, PS-*

It would be awesome if the configuration of this gem would allow for using different algorithms
 - specifying the algorithm via ENV
 - more modular approach to allow using different algorithms in the code

**Comment by waiting-for-dev** [comment]
I'm reluctant to add new algorithms if there is no real need. I mean, for a security related library, having less lines of code means having less attack surface. Could you share your use case for this new feature?

**Comment by waiting-for-dev** [comment]
Closing because the lack of feedback, but feel free to add more comments if you are still interested in this issue.
