### ISSUE TITLE
Is there a reason that `store?` is hardcoded as false?

### ISSUE THREAD

**Issue by connor-odoherty** [waiting-for-dev/warden-jwt_auth#20]
Is there a reason why we would never, ever want to store a user session after using JWT to authenticate them?

**Comment by waiting-for-dev** [comment]
Because if you are going to use session you are better off with old friend and battle tested cookies for authentication.

**Comment by connor-odoherty** [comment]
@waiting-for-dev  Ah, so here is the use case:

I am building an app that works for iOS and Android. In this app, I have a WebView. When launching the WebView,  I send a JWT token up in the auth header so that the user is immediately logged in. Up until iOS 13, this worked great on both Android and iOS.

However, iOS 13 has introduced quite a few issues surround cookies in their WebView product: https://bugs.webkit.org/show_bug.cgi?id=200857

So, when I use this strategy on Android, the cookie is returned with a "warden.user.user.key" key-value pair, which lets me continue to stay logged in on the session, even after a redirect or form submission.

However, when I use the exact same strategy on iOS 13, the cookie does not return "warden.user.user.key" at all. As soon as I navigate beyond the first page of the WebView, I get an "unauthenticated" error.

When I monkey-patch the JWTAuth::Strategy like so:

```
module Warden
  module JWTAuth
    class Strategy
      def store?
        true
      end
    end
  end
end
```

the WebView behaves as expected.

In this case, is saving the session like I did still inadvisable?

What's odd to me is that when logging in through Android, store is still set to false. Do you have any ideas as to why Android still recieves the session cookie even though `store?` is false, and iOS doesn't?

Thanks again for the help!

**Comment by waiting-for-dev** [comment]
When you store a user in the session warden will authenticate from it without even reaching any strategy. So, in fact, if you authenticate with some strategy (being it `:jwt` or `:database_authenticatable` in devise, for example) which stores to the session, following calls will not use any strategy. This means that you can send any token and the user will be authenticated, even if it is incorrect, as the `:jwt` strategy is not used. So it makes no sense to `store?`...

**Comment by waiting-for-dev** [comment]
I guess I can close it. Feel free to add more comments if needed.
