### ISSUE TITLE
Wrong dependencies in gemspec?

### ISSUE THREAD

**Issue by viamin** [waiting-for-dev/warden-jwt_auth#27]
I'm running into https://github.com/waiting-for-dev/devise-jwt/issues/172, which recommends upgrading to 0.4.2, but the gemspec dependency prevents updating. 

Latest `warden-jwt_auth` (0.4.2) uses the latest `dry-configurable` (which I think contains the fix for https://github.com/waiting-for-dev/warden-jwt_auth/issues/22)

The warden-jwt_auth v0.4.2 gemspec has this dependency:
`spec.add_dependency 'dry-configurable', '~> 0.9', '< 0.11'`

In 0.4.1, the gemspec has this:
`spec.add_dependency 'dry-configurable', '~> 0.11', '>= 0.11.3'`

My current Gemfile.lock has these versions (and I'm hitting #172):
```
    devise (4.7.1)
    devise-jwt (0.6.0)
    dry-configurable (0.11.5)
    warden-jwt_auth (0.4.1)
```
My working config (before upgrading and with locked versions of dry-configurable and warden-jwt_auth) is this:
```
    devise (4.7.1)
    devise-jwt (0.6.0)
    dry-configurable (0.9.0)
    warden-jwt_auth (0.4.0)
```

**Comment by viamin** [comment]
Makes sense, sorry about the noise. Closing.

**Comment by waiting-for-dev** [comment]
No worries
