### ISSUE TITLE
JWT::ExpiredSignature exception trying to revoke an expired token

### ISSUE THREAD

**Issue by sergiogomez** [waiting-for-dev/warden-jwt_auth#3]
Hello. TokenDecoder calls directly to JWT.decode without handle expiration claim as seen at https://github.com/jwt/ruby-jwt#expiration-time-claim and it raises an exception when token is expired.

**Comment by waiting-for-dev** [comment]
Hi @sergiogomez . TokenDecoder is a lower level class. The exception is rescued from the [warden strategy](https://github.com/waiting-for-dev/warden-jwt_auth/blob/5aceb72443937200c17bd485f34609f3d87bf1c8/lib/warden/jwt_auth/strategy.rb#L21). There, if the token is expired or there is any other kind of decoding error authentication fails.

**Comment by sergiogomez** [comment]
Thanks @waiting-for-dev but error come from the method 'call' from TokenRevoker class, that is used at middleware and it can't be rescued without another middleware, monkey patch or any other workaround (eg. removing 'HTTP_AUTHORIZATION' header if user is not authenticated).

**Comment by sergiogomez** [comment]
And I forgot to say you that the exception is not rescued from the [warden strategy](https://github.com/waiting-for-dev/warden-jwt_auth/blob/5aceb72443937200c17bd485f34609f3d87bf1c8/lib/warden/jwt_auth/strategy.rb#L21), if method 'authenticate! is not called. It's raised at [revocation_manager middleware](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/middleware/revocation_manager.rb#L21)

**Comment by waiting-for-dev** [comment]
I see. So, you are trying to revoke a token that is no longer valid, isn't it? I think it is quite an edge case, which could arise if a user has been idle until the expiration time has reached and then she requests, for example, to sign out. Or maybe it could also arise if a custom token administration page (for several devices) is implemented.

When I have the time (soon) I will change `TokenRevoker` so it handles this scenario.

**Comment by sergiogomez** [comment]
Exactly, it's a sign out from an authenticated user with an expired token ;)

**Comment by waiting-for-dev** [comment]
Hey @sergiogomez , not sure we should do something here. Is your `sign_out` request under authentication? If so, the revocation layer should not be reached (so then the error should not arise), because warden failure application should abort the middleware chain before reaching there. If it is under authentication, could you tell me which failure application are you using?

**Comment by zjuanma** [comment]
I have this error too.

`JWT::ExpiredSignature (Signature has expired):
  
.bundle/gems/jwt-1.5.6/lib/jwt/verify.rb:47:in `verify_expiration'
.bundle/gems/jwt-1.5.6/lib/jwt/verify.rb:10:in `block (2 levels) in singleton class'
.bundle/gems/jwt-1.5.6/lib/jwt/decode.rb:53:in `block in verify'
.bundle/gems/jwt-1.5.6/lib/jwt/decode.rb:50:in `each'
.bundle/gems/jwt-1.5.6/lib/jwt/decode.rb:50:in `verify'
.bundle/gems/jwt-1.5.6/lib/jwt.rb:126:in `decode'
.bundle/gems/warden-jwt_auth-0.1.0/lib/warden/jwt_auth/token_decoder.rb:14:in `call'
.bundle/gems/warden-jwt_auth-0.1.0/lib/warden/jwt_auth/token_revoker.rb:13:in `call'
.bundle/gems/warden-jwt_auth-0.1.0/lib/warden/jwt_auth/middleware/revocation_manager.rb:30:in `revoke_token'
.bundle/gems/warden-jwt_auth-0.1.0/lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
.bundle/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
.bundle/gems/rack-2.0.1/lib/rack/builder.rb:153:in `call'
.bundle/gems/rollbar-2.14.0/lib/rollbar/middleware/rack/builder.rb:16:in `block in call_with_rollbar'
.bundle/gems/rollbar-2.14.0/lib/rollbar.rb:145:in `scoped'
.bundle/gems/rollbar-2.14.0/lib/rollbar/middleware/rack/builder.rb:14:in `call_with_rollbar'
.bundle/gems/warden-jwt_auth-0.1.0/lib/warden/jwt_auth/middleware.rb:23:in `call'
.bundle/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
.bundle/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
.bundle/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
.bundle/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
........
`

**Comment by waiting-for-dev** [comment]
@zjuanma what are you trying to do? Is it during a sign out? If so, is this request authenticated?

**Comment by zjuanma** [comment]
Yes, it is during a sign out and the request is authenticated.

`Request URL:http://xxxxxx/auth/logout
Request Method:DELETE
Status Code:500 Internal Server Error
Remote Address:127.0.0.1:80
Referrer Policy:no-referrer-when-downgrade`

`accept:application/json
Accept-Encoding:gzip, deflate, sdch
Accept-Language:es-ES,es;q=0.8,en;q=0.6,gl;q=0.4
authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb250YWN0X25hbWUiOiJBZG1pbiIsInN1YiI6Miwic2NwIjoidXNlciIsImlhdCI6MTQ5MDc3MjA2NywiZXhwIjoxNDkwNzcyMDgyLCJqdGkiOiI1NzU4NjJlMC1lMDA2LTRiZDYtOTIzMC0yYWQ3MzZmODM5OWIifQ.C7o1nqa89ETmIL2aoa0MrItOLCQ7pKQ_UEk-6H7euq8
Connection:keep-alive
content-type:application/json
Host:xxxxxx
Origin:http://xxxxxx
Referer:http://xxxxxx/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36`

**Comment by waiting-for-dev** [comment]
Could you tell me which warden failure application are you using?

**Comment by sergiogomez** [comment]
This is my workaround to the same problem:

https://gist.github.com/sergiogomez/063614070c1ed105d488a8eda937e0b0

**Comment by waiting-for-dev** [comment]
This could be solved without the need of a workaround, but first it would be nice to understand why it is happening. Right now, I don't understand why. If I'm not wrong, if your sign out request is under authentication, it should be intercepted by the warden failure application, which should render a `401` response, without even reaching to the recovation middleware.

**Comment by zjuanma** [comment]
@waiting-for-dev 
I have this.

module Devise
  class CustomAuthFailure < Devise::FailureApp
    def respond
      self.status = 401
      self.content_type = 'json'
      self.response_body = {"errors" => ["Invalid login credentials"]}.to_json
    end
  end
end

**Comment by waiting-for-dev** [comment]
Thanks. I'l look into it

**Comment by waiting-for-dev** [comment]
Hey @zjuanma @sergiogomez , could you please confirm that branch `expired_in_sign_out-3` fixes your issue?

**Comment by waiting-for-dev** [comment]
Well, it works in my tests. Released in version 0.1.2, which is now also required by devise-jwt 0.2.1.

**Comment by sergiogomez** [comment]
Hey @waiting-for-dev , Just tested, and now it works ok. Thank you very much!! ;)
