### ISSUE TITLE
Authentication Only using Outside IDP?

### ISSUE THREAD

**Issue by xcskier56** [waiting-for-dev/warden-jwt_auth#31]
Hi there! We have a microservice architecture that uses our own IDP to generated JWTs, and then to authenticate, we verify them in the other services using the public key of the IDP. We're looking at refactoring/improving the authentication story for our services. 

Can this library be used solely to authenticate an incoming request? I don't want to revoke the token, or return a new one. Simply want to authenticate the incoming request using the Bearer token. Is this doable?

**Comment by waiting-for-dev** [comment]
Probably you're better off using just [ruby-jwt](https://github.com/jwt/ruby-jwt), which is a dependency here.

**Comment by xcskier56** [comment]
Cool. Thanks!
