### ISSUE TITLE
Problems with dry-configurable 0.13.0

### ISSUE THREAD

**Issue by pollinoco** [waiting-for-dev/warden-jwt_auth#35]
.rvm/gems/ruby-2.7.2/gems/warden-jwt_auth-0.5.0/lib/warden/jwt_auth.rb:19:in `<module:Warden>' [dry-configurable] default value as positional argument to settings is deprecated and will be removed in the next major version
Provide a `default:` keyword argument instead

**Comment by waiting-for-dev** [comment]
It's fixed by #33. I need to release a new version, though. I'll do it as soon as possible.

**Comment by waiting-for-dev** [comment]
Released on v0.6.0
