### ISSUE TITLE
Add ability to customize error messages

### ISSUE THREAD

**Issue by richardboehme** [waiting-for-dev/warden-jwt_auth#39]
Hey! Thanks for the great gem!

It would be cool if it's possible to customize the error messages thrown for example by the `UserDecoder` class. My idea would be to make these messages configurable through the configuration of this gem. If the general idea gets approved I'd be happy to help out by working on this!

**Use Case:**

I'm currently using this gem together with devise-jwt and would like to get a consistent API error message schema. To be precise I'd like to overwrite the 'revoked token' message. My current work around is to define a custom failure app for warden and overwrite the message manually. Ideally it would be great to overwrite the message in `warden-jwt_auth` to remove the work around.

**Comment by waiting-for-dev** [comment]
Hey @richardboehme, thanks for your predisposal to help. [`UserDecoder`](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/user_decoder.rb) doesn't render any error. It raises an error, so it's already Devise or your app the one that is catching it and decorating it as an error message. It's there where you need to adjust the format.

**Comment by richardboehme** [comment]
Hey @waiting-for-dev I think you are right. My issue might be pretty devise-specific because they expect a symbol as the warden failure message to translate it using i18n. All in all I guess my workaround with the custom warden failure app might be the proper solution to my problem!
