### ISSUE TITLE
When i updated the gem to 0.7.0, my users have been disconnected

### ISSUE THREAD

**Issue by cprodhomme** [waiting-for-dev/warden-jwt_auth#45]
## Expected behavior

When i updated the gem version 0.6.0 to 0.7.0 i expected not i have break changes like it's say in [Semantic Versionning](https://semver.org/)

Should have released a major version :) (maybe 1.0.0)

## Steps to Reproduce the Problem

1. Deploy app with warden-jwt_auth 0.6.0
2. Connect as user
3. Update the gem to 0.7.0 and deploy
4. Go to your app and see that your have been disconnected

**Comment by waiting-for-dev** [comment]
Thanks for reporting. Could you please fill in all the information requested in the bug report template? Thanks!
