### ISSUE TITLE
Config model mapping works only with default key

### ISSUE THREAD

**Issue by tejasbubane** [waiting-for-dev/warden-jwt_auth#6]
The README has this model mapping:

```
config.mappings = { user: UserRepository }
```
and revocation strategy:

```
config.revocation_strategies = { user: RevocationStrategy }
```

This does not seem to work for me. It does not send the JWT token in the header for login - no error shown.

Wiki uses `default` instead of `user` as key. I have taken the example in wiki and replaced the key `default` with `user` and it stops working. Does not work with any other key except `default`. Is `default` the expected key?

You can find the code in [this gist](https://gist.github.com/tejasbubane/994bca140a9923362ad23b18f076769f).

**Comment by waiting-for-dev** [comment]
Warden defaults to `default` scope, and otherwise you have to tell it.

So, you have to use:

```ruby
env['warden'].authenticate!(scope: :user)
env['warden'].set_user(User.instance, store: false, scope: :user)
```

instead that current:

```ruby
env['warden'].authenticate!
env['warden'].set_user(User.instance, store: false)
```
That's warden API.

**Comment by tejasbubane** [comment]
Thanks! 👍 
I missed overlooked `warden scope` from the README and assumed that to be this gem's API for config.
