### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by janosrusiczki** [waiting-for-dev/warden-jwt_auth#61]
As you may know I'm maintaining [a fork of this repo](https://github.com/photonia-io/warden-jwt_auth/) which includes some changes from [this PR](https://github.com/waiting-for-dev/warden-jwt_auth/pull/47) that was not accepted, but which I need.

I was trying to update devise-jwt in my project, but it said it requires warden-jwt_auth >= 0.10. I synced my fork, but I noticed that [the version defined in the code is 0.9.0](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/version.rb) while the [gem version is 0.10.0](https://rubygems.org/gems/warden-jwt_auth/versions/0.10.0).

Could you please push the updated code to the repo?

**Comment by waiting-for-dev** [comment]
I just released 0.10.1 with the version mismatch fixed. Thanks for reporting.
